version: '3.8'
name: "ecommerce"

services:
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/ecommerce
      - IMAGE_URL_PREFIX=/images
    depends_on:
      - mongodb
    networks:
      - app-network
      - mongodb-network
    volumes:
      - ./upload:/app/upload
      - ./backend:/app

  admin:
    platform: linux/amd64
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=/admin
      - REACT_APP_API_URL=/api
      - REACT_APP_IMAGE_URL=/images
    networks:
      - app-network
    volumes:
      - ./admin:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=/api
      - REACT_APP_IMAGE_URL=/images
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - admin
      - frontend
    networks:
      - app-network
    volumes:
      - ./upload:/app/upload

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mongodb-network
      - app-network

volumes:
  mongodb_data: 

networks:
  app-network:
    driver: bridge
  mongodb-network:
    driver: bridge
