version: '3.8'
name: "ecommerce"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - admin
      - frontend
    networks:
      - app-network
    volumes:
      - ./upload:/app/upload

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/mydatabase?authSource=admin
      - IMAGE_URL_PREFIX=/images
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./upload:/app/upload

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=/admin
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=/api
      - REACT_APP_IMAGE_URL=/images
    depends_on:
      - backend
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data: 

networks:
  app-network:
    driver: bridge 
