version: '3.8'
name: "ecommerce"

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://root:examplepassword@mongodb:27017/mydatabase?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./upload:/app/upload

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:4000
    depends_on:
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:4000
    depends_on:
      - backend
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=examplepassword
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data: 

networks:
  app-network:
    driver: bridge 
